site_name: Faust Registry
title_brand: Registry
site_description: Faust Registry Documentation.
copyright: Copyright &copy; 2019-2024 <a href="https://www.grame.fr">Grame-CNCM</a>
nav:
- Overview:
  - ' Organization ': organization.md
  - ' Standard Functions ': standardFunctions.md
  - ' Contributing ': contributing.md
  - ' Community ': community.md
  - ' Copyright/License ': about.md
- About: about.md
- Contributors:
  - faust: contributors/faust/overview.md
theme:
  name: mkdocs
  navigation_depth: 3
  custom_dir: theme/
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
- mdx_math
- toc:
    baselevel: 1
site_dir: ../docs
extra_css:
- css/extra.css
